name: Cron Job Validation
# on:
#   schedule:
#     - cron: "*/10 * * * *"
on:
  pull_request:
  push:

jobs:
  validation:
    name: Suggest Chain Validation Check
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - run: npm install
      - run: npm install --global yarn

      - name: Fetch action
        id: fetch
        uses: Rishabh510/Path-lister-action@master
        with:
          path: "cosmos/"
          type: ".json"

      - name: Output results
        run: |
          for file in ${{ steps.fetch.outputs.paths }}; do
          if [[ $file == *".json"* ]]; then
              yarn ts-node src/index.ts $file
            fi
          done
