name: Pull Request Validation
on:
  pull_request:
  push:

jobs:
  validation:
    name: Pull Request Suggest Chain Validation
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - run: npm install
      - run: npm install --global yarn
      - run: yarn dev
