name: Validation
on:
  pull_request_target:
    types: [opened]

jobs:
  test:
    name: validation to suggestchain
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout to master branch
        uses: actions/checkout@master
      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - run: npm install --global yarn
      - run: sudo apt-get update
      - uses: actions/github-script@v6
        id: set-result
        with:
          script: |
            const validator = require("./script/validator.js");
            const checkValidateResult = await validator.checkValidate();
            return checkValidateResult;
      - name: Print result
        run: echo "${{steps.set-result.outputs.result}}"
      - uses: actions/github-script@v6
        with:
          github-token: ${{secrets.VALIDATION_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Hello~~~'
            });
