name: Validation
on:
  pull_request:
  push:


jobs:
  test:
    name: validation to suggestchain
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - run: npm install --global yarn
      - run: sudo apt-get update
      - name: validation to suggestChains
        uses: actions/github-script@v6
        id: set-result
        with:
          script: |
            const validator = require("./src/validator.js");
            const checkValidateResult = await validator.checkValidate();
            if (!checkValidateResult.isValid) {
              throw new Error(checkValidateResult.error);
            }
