name: Validation
on:
  pull_request:
  push:

jobs:
  test:
    name: validation to suggestchain
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout to master branch
        uses: actions/checkout@master
      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install --global yarn
      - run: sudo apt-get update
      - name: Test hello world
        run: echo "hello world333!"
      - uses: actions/github-script@v6
        with:
          github-token: ${{secrets.VALIDATION_TOKEN}}
          script: |
            const ref = "${{github.ref}}"
            const pull_number = Number(ref.split("/")[2])
            await github.pulls.createReview({
              ...context.repo,
              pull_number,
              body:"hello~~~ ",
              event: "REQUEST_CHANGES"
            })
            await github.pulls.update({
              ...context.repo,
              pull_number,
              state: "closed"
            })
      
